apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog-deployment
  namespace: koyama
  labels:
    app: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog:v1.0.0
        ports:
        - containerPort: 1025
        - containerPort: 8025
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog-service
  namespace: koyama
spec:
  selector:
    app: mailhog
  ports:
    - name: smtp-server
      protocol: TCP
      port: 2500
      targetPort: 8025
    - name: web-ui
      protocol: TCP
      port: 2525
      targetPort: 1025
  externalIPs:
    - 192.168.210.21
    - 192.168.210.22
    - 192.168.210.23
