apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv
  namespace: ghost
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ghost-storage
  local:
    path: /opt/k3s-pv/ghost
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rudder-1
