apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  namespace: ghost
spec:
  type: clusterIP
  selector:
    app: ghost
  ports:
  - protocol: TCP
    port: 2368
#    targetPort: 2368
  type: ClusterIP
  externalIPs:
    - 192.168.210.21

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ghost
  namespace: ghost
spec:
  selector:
    matchLabels:
      app: ghost
  serviceName: "ghost"
  replicas: 1
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:3-alpine
        env:
        - name: url
          value: "https://rudder.tak-cslab.org/2020-ug3/"
        ports:
        - containerPort: 2368
          name: ghost
        volumeMounts:
        - name: ghost-pvc
          mountPath: /var/lib/ghost/content
  volumeClaimTemplates:
  - metadata:
      name: ghost-pvc
      namespace: ghost
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ghost-storage"
      resources:
        requests:
          storage: 1Gi
