apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/ghost
    type: DirectoryOrCreate
  storageClassName: ghost-storage
