apiVersion: apps/v1
kind: Deployment
metadata:
  name: slacker-deployment
  namespace: koyama
  labels:
    app: slacker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: slacker
  template:
    metadata:
      labels:
        app: slacker
    spec:
      containers:
      - name: slacker
        image: ontrif/slacker:0.1.0
        ports:
        - containerPort: 8025
        env:
        - name: http_proxy
          value: 'http://192.168.210.1:8080/'
        - name: https_proxy
          value: 'http://192.168.210.1:8080/'
        volumeMounts:
        - name: config-volume
          mountPath: /etc/slacker
      volumes:
        - name: config-volume
          configMap:
            name: slacker-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: slacker-service
  namespace: koyama
spec:
  selector:
    app: slacker
  ports:
    - protocol: TCP
      port: 2525
      targetPort: 8025
  externalIPs:
    - 192.168.210.21
    - 192.168.210.22
    - 192.168.210.23
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slacker-configmap
  namespace: koyama
data:
  config.yml: |
    default:
        channel: '#lab-assignments-2020-email'
        username: slacker
        icon_url: ''
        slack_token: 'xoxb-xxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        debug: false
    rules:
        - name: test-rule
          from: '.*@hoge.local'
          options:
              username: slacker
              channel: '#lab-assignments-2020-email'
              icon_url: ''
              debug: false
